---
title: "Import Growth symmetry data"
author: "Douglas A. Campbell, Sylwia Sliwinska-Wilczewska"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# knitr::opts_chunk$set(fig.path='Figs/')
```

```{r set project variables}
Project <- "Baltic_Photoperiod"
DataOut <- file.path("..", "Data", "ImportedData")

FileID <- "Smooth"
FileEncode <- "UTF-8" 
Delimiter <- ""
HeaderRows <- 0
```

```{r load libraries} 
library(tidyverse)
library(lubridate)
library(stringr)
library(broom)
library(knitr)
library(OneR)
library(zoo)
library(strucchange)
library(magrittr)
library(googledrive)
library(googlesheets4)
library(readxl)
```

```{r load local multiculticatalog, message = FALSE, warning = FALSE, echo=FALSE}
gs4_deauth()

MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1y144Qjs1pxO2vYU4G6of69qX1TVlA8WTwnhfVwaSU0U/edit#gid=0") %>%
  drop_na(WL) %>%
  mutate(WL = unlist(WL))

as.data.frame(MetaData)
MetaData <- MetaData %>%
   mutate(ExpDate = ymd(ExpDate),
          ExpEndDate = ymd_hms(`ExpEndDate`))
```

```{r Load local GS catalog, message = FALSE, warning = FALSE, echo=FALSE}
gs4_deauth()

GScatalog<- read_sheet("https://docs.google.com/spreadsheets/d/1zqH6iYlqMPigyloLKJPeVWugmcnmgJ-eMU3gLkR6FSU/edit#gid=0")

as.data.frame(GScatalog)
GScatalog <- GScatalog 
```
```{r Prepare data - mutate as numeric, calculate AccLen, DecLen, GS (growth symmetry)}
GScatalog <- GScatalog %>% 
  mutate(Acc_perc = as.numeric(Acc_perc)) %>% 
  mutate(Dec_perc = as.numeric(Dec_perc)) %>% 
  mutate(AccDecRatio_perc = Acc_perc/Dec_perc) %>% 
  mutate(Par_ue = as.numeric(Par_ue)) %>% 
  mutate(Photoperiod = as.numeric(Photoperiod)) %>%
  mutate(tMaxAG = as.numeric(tMaxAG)) %>%
  mutate(tMaxDG = as.numeric(tMaxDG)) %>%
  mutate(PhotoperiodTstart_h=as.numeric(PhotoperiodTstart_h)) %>% 
  mutate(PhotoperiodTend_h=as.numeric(PhotoperiodTend_h)) %>% 
  mutate(AccLen = tMaxDG-PhotoperiodTstart_h) %>% 
  mutate(DecLen = PhotoperiodTend_h-tMaxDG) %>% 
  mutate(GS = AccLen/DecLen) %>% 
  mutate(TDG = as.numeric(TDG)) 
```

```{r Merge GS catalog with MetaData, warning = FALSE}
GScatalogMeta <- MetaData %>%
  left_join(., GScatalog, by = c("Strain" = "Strain", "Photoperiod"="Photoperiod", "Par_ue"="Par_ue","WL"="WL", "O2"="O2")) 
```

```{r Cleaning unrelated values and outliers/error points}
GScatalogMeta<-GScatalogMeta %>% 
  filter(Photoperiod!=24) %>% 
  filter(AccDecRatio_perc<10)
  
GScatalogMeta1 <-GScatalogMeta %>% 
  filter(PARPhotonDose>=19440000) %>% 
  filter(GS<=2)
GScatalogMeta2 <-GScatalogMeta %>% 
  filter(PARPhotonDose<19440000) %>% 
filter(GS<4)
GScatalogMeta<-rbind(GScatalogMeta1,GScatalogMeta2)
rm(GScatalogMeta1,GScatalogMeta2)
```

```{r Calculate mean of GS from every day (every peak in exp and pre-stationary phase)}
GScatalogMeta<-GScatalogMeta %>% 
  group_by(Strain, Photoperiod, Par_ue, Phase) %>%
  summarize(Run, CultureID, Strain, InnocDate, ExpDate, Par_ue, Photoperiod, PARPhotonDose, MC, Tube, O2, LightShape, ExpEndDate,  PhotoperiodTstart_h, PhotoperiodTend_h,tMaxDG,tMaxAG, Phase, AchivePreStationary, MaxDG, MaxAG, Acc_perc, Dec_perc, Strain, Par_ue, Photoperiod, O2, WL, OD680start, OD680end, TDG, AccDecRatio_perc, AccLen, DecLen, GS, 
            meanAccLen = mean(AccLen), 
            sdAccLen = sd(AccLen),
            meanDecLen = mean(DecLen), 
            sdDecLen = sd(DecLen),
            meanGS = mean(GS), 
            sdGS = sd(GS)) %>%  
  ungroup() 
```

```{r Change strain names for plot}
GScatalogMeta<-GScatalogMeta %>% 
    mutate(Strain=case_when(Strain=="BA127R"~"PE-rich_127",
         Strain=="BA48R"~"PE-rich_048",
        Strain=="BA56G"~"PC-rich_056",
         Strain=="BA77G"~"PC-rich_077"))
```

```{r Create facets labels for plot}
GScatalogMeta$facetsPar_ue = factor(GScatalogMeta$O2, labels = c("PAR~(µmol~photons~m^{-2}~s^{-1})"))
GScatalogMeta$facetsPhotoperiod = factor(GScatalogMeta$WL, labels = c("Photoperiod~(h)"))
GScatalogMeta$facetsStrain = factor(GScatalogMeta$O2, labels = c("Strain"))
GScatalogMeta$facetsPhase = factor(GScatalogMeta$WL, labels = c("Phase~of~growth"))
```

```{r Create df to show hline}
data_hlineGS8 <- data.frame(Photoperiod= c(8),facets2= c("Photoperiod~(h)"),value = c(4))
data_hlineGS12 <- data.frame(Photoperiod= c(12),facets2= c("Photoperiod~(h)"),value = c(6))
data_hlineGS16 <- data.frame(Photoperiod= c(16),facets2= c("Photoperiod~(h)"),value = c(8))
```

```{r Create GS plot, fig.height = 8, fig.width = 8, warning = FALSE}

scientific_10 <- function(x) {   parse(text=gsub("e\\+*", " %*% 10^", scales::scientific_format()(x))) }
lab1=c(expression("8 h"), expression("12 h"), expression("16 h"))
lab2=c(expression("30 µE"), expression("90 µE"), expression("180 µE"), expression("300 µE"), expression("900 µE"))

GScatalogMeta %>%
  ggplot() +
  geom_point(aes(x = PARPhotonDose, y = meanGS, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
  geom_errorbar(aes(x = PARPhotonDose, ymin = meanGS - sdGS, ymax = meanGS + sdGS, colour = as.factor(Par_ue)), show.legend = F) +
  geom_hline(yintercept = 1, linetype="dashed") +
   labs(y = "Diel growth symmetry (AccLen/DecLen)", x = "PAR photon dose ( µmol photons "~m^-2~""~d^-1~")") +
  scale_shape_manual(values = c(15, 16, 17), name="", labels = lab1) +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  scale_x_continuous(label=scientific_10) +
  ggh4x::facet_nested(cols = vars(Phase), rows = vars(Strain), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="white"),
        legend.position = c(0.92,0.89),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.title = element_blank(),
        legend.text = element_text(size=10))

```

```{r Fitting exponential decays}
GScatalogMetaExp <-GScatalogMeta %>% 
  drop_na(GS) %>%
  filter(Phase == "Exponential") %>% 
  select(c(GS, PARPhotonDose, Strain)) %>% 
  mutate(y=GS) %>% 
  mutate(t=PARPhotonDose) %>% 
  select(-c(GS, PARPhotonDose)) %>% 
  select(t, y, Strain)
qplot(t, y, data = GScatalogMetaExp, colour = Strain)

# Fit the data
fitted <- GScatalogMetaExp %>% 
  nest(-Strain) %>%
  mutate(
    fit = map(data, ~nls(y ~ SSasymp(t, yf, y0, log_alpha), data = .)),
    tidied = map(fit, tidy),
    augmented = map(fit, augment)) 

fitted2<-fitted %>% 
  unnest(tidied) %>% 
  select(Strain, term, estimate) %>% 
pivot_wider(., names_from = c(term), values_from = c(estimate)) %>% 
  mutate(alpha = exp(log_alpha)) 
```


mutate for nice plot PAR photon Dose 590 and 445
```{r}
augmented590 <- augmented590 %>% 
  mutate(Ex_WL=Strain) %>% 
      mutate(Ex_WL=case_when(Ex_WL=="PE-rich_127"~590,
         Ex_WL=="PE-rich_048"~590,
        Ex_WL=="PC-rich_056"~590,
         Ex_WL=="PC-rich_077"~590)) %>% 
  mutate(Ex_WL = as.factor(Ex_WL)) %>% 
  mutate(O2=Ex_WL) %>% 
  mutate(O2=case_when(O2==590~21)) %>% 
  mutate(WL=Ex_WL) %>% 
  mutate(WL=case_when(WL==590~"WW")) 

augmented590dark <- augmented590dark %>% 
  mutate(Ex_WL=Strain) %>% 
      mutate(Ex_WL=case_when(Ex_WL=="PE-rich_127"~590,
         Ex_WL=="PE-rich_048"~590,
        Ex_WL=="PC-rich_056"~590,
         Ex_WL=="PC-rich_077"~590)) %>% 
  mutate(Ex_WL = as.factor(Ex_WL)) %>% 
  mutate(O2=Ex_WL) %>% 
  mutate(O2=case_when(O2==590~21)) %>% 
  mutate(WL=Ex_WL) %>% 
  mutate(WL=case_when(WL==590~"WW")) 



```
```{r Create GS plot, fig.height = 8, fig.width = 8, warning = FALSE}

scientific_10 <- function(x) {   parse(text=gsub("e\\+*", " %*% 10^", scales::scientific_format()(x))) }
lab1=c(expression("8 h"), expression("12 h"), expression("16 h"))
lab2=c(expression("30 µE"), expression("90 µE"), expression("180 µE"), expression("300 µE"), expression("900 µE"))


  ggplot(GScatalogMeta, aes(x = PARPhotonDose, y = meanGS)) +
  geom_point(aes(x = PARPhotonDose, y = meanGS, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
  geom_errorbar(aes(x = PARPhotonDose, ymin = meanGS - sdGS, ymax = meanGS + sdGS, colour = as.factor(Par_ue)), show.legend = F) +
  
  geom_line(aes(t, .fitted), show.legend = F, augmented) +
  
  
  geom_hline(yintercept = 1, linetype="dashed") +
   labs(y = "Diel growth symmetry (AccLen/DecLen)", x = "PAR photon dose ( µmol photons "~m^-2~""~d^-1~")") +
  scale_shape_manual(values = c(15, 16, 17), name="", labels = lab1) +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  scale_x_continuous(label=scientific_10) +
  ggh4x::facet_nested(cols = vars(Phase), rows = vars(Strain), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="white"),
        legend.position = c(0.92,0.89),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.title = element_blank(),
        legend.text = element_text(size=10))

```






```{r AccLen vs PARphotondose Plot, fig.height = 8, fig.width = 8, warning = FALSE}

scientific_10 <- function(x) {   parse(text=gsub("e\\+*", " %*% 10^", scales::scientific_format()(x))) }
lab1=c(expression("8 h"), expression("12 h"), expression("16 h"))
lab2=c(expression("30 µE"), expression("90 µE"), expression("180 µE"), expression("300 µE"), expression("900 µE"))

GScatalogMeta %>%
  filter(meanAccLen>0) %>% 
  ggplot() +
  geom_point(aes(x = PARPhotonDose, y = meanAccLen, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
    geom_line(aes(x = PARPhotonDose, y = meanAccLen, colour = as.factor(Par_ue)), size = 0.7, show.legend = F) +
  geom_errorbar(aes(x = PARPhotonDose, ymin = meanAccLen - sdAccLen, ymax = meanAccLen + sdAccLen, colour = as.factor(Par_ue)), show.legend = F, width=0) +
  geom_hline(data = data_hlineGS8, aes(yintercept = value), linetype="dotted") +
  geom_hline(data = data_hlineGS12, aes(yintercept = value), linetype="dotdash") +
  geom_hline(data = data_hlineGS16, aes(yintercept = value), linetype="dashed") +
   labs(y = "AccLen (h)", x = "PAR photon dose ( µmol photons "~m^-2~""~d^-1~")") +
  scale_shape_manual(values = c(15, 16, 17), name="", labels = lab1) +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  scale_x_continuous(label=scientific_10) +
  scale_y_continuous(breaks=seq(0, 10, by = 2.5)) +
  coord_cartesian(ylim = c(0, 12.5)) +
  ggh4x::facet_nested(cols = vars(facetsPhase, Phase), rows = vars(facetsStrain, Strain), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="white"),
        legend.position = c(0.92,0.89),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.title = element_blank(),
        legend.text = element_text(size=10))


GScatalogMeta %>%
  filter(meanAccLen>0) %>% 
  ggplot() +
  geom_point(aes(x = Photoperiod, y = meanAccLen, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
    geom_errorbar(aes(x = Photoperiod, ymin = meanAccLen - sdAccLen, ymax = meanAccLen + sdAccLen, colour = as.factor(Par_ue)), show.legend = F, width=0) +
labs(y = "AccLen (h)", x = "Photoperiod (h)") +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  geom_abline(slope = 0.5, intercept = 0, linetype = "dashed") +
  scale_y_continuous(breaks=seq(0, 10, by = 2.5)) +
  coord_cartesian(ylim = c(0, 12.5)) +
  ggh4x::facet_nested(cols = vars(facetsPhase, Phase), rows = vars(facetsStrain, Strain), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        panel.spacing.x = unit(1,"lines"),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.88,0.89),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.title = element_blank(),
        legend.text = element_text(size=10))
```


TDG


```{r Create df for vertical lines (coloured as Strain) contained tMaxAG values}
#PC-rich_056
data_vline_056 <- data.frame(Par_ue= c(30, 90, 180, 300, 900,30, 90, 180, 300, 900,30, 90, 180, 300, 900),Photoperiod= c(8,8,8,8,8,12,12,12,12,12,16,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(293.8333, 375.6500, 266.84, 240.72, 187.73, 353.10, 296.45, 217.80, 191.03, 188.19, 355.30, 191.49, 114.95, 112.75, 163.44))

#PC-rich_077
data_vline_077 <- data.frame(Par_ue= c(30, 90, 180, 300, 900,30, 90, 180, 300, 900,30, 90, 180, 300, 900),Photoperiod= c(8,8,8,8,8,12,12,12,12,12,16,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(244.2500, 348.2400, 266.9300, 215.42, 187.18, 349.80, 244.38, 190.39, 163.62, 184.16, 299.57, 168.85, 137.50, 112.29, 161.97))

#PE-rich_048
data_vline_048 <- data.frame(Par_ue= c(30, 90, 180, 300, 900,30, 90, 180, 300, 900,30, 90, 180, 300, 900),Photoperiod= c(8,8,8,8,8,12,12,12,12,12,16,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(347.1400, 319.9200, 240.8100, 214.41, 187.27, 350.17, 216.33, 163.44, 136.03, 135.39, 299.38, 166.28, 137.32, 111.28, 109.45))

#PE-rich_127
data_vline_127 <- data.frame(Par_ue= c(30, 90, 180, 300, 900,30, 90, 180, 300, 900,30, 90, 180, 300, 900),Photoperiod= c(8,8,8,8,8,12,12,12,12,12,16,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(373.2700, 321.0200, 240.9000, 187.92, 187.00, 371.98, 245.39, 189.48, 162.62, 188.38, 382.07, 168.39, 113.76, 111.56, 135.76))
```

```{r Create TDG plot, fig.height = 8, fig.width = 8, warning = FALSE}
GScatalogMeta %>%
  filter(Photoperiod != 24) %>% 
  ggplot() +
  geom_point(aes(x = PhotoperiodTend_h, y = TDG, colour = as.factor(Strain)), size = 3.5, alpha = 0.8, show.legend = T) +
  geom_vline(data = data_vline_056, aes(xintercept = value), linetype="dotdash", colour = "seagreen4") +
  geom_vline(data = data_vline_077, aes(xintercept = value), linetype="dotdash", colour = "palegreen3") +
  geom_vline(data = data_vline_048, aes(xintercept = value), linetype="dotdash", colour = "brown4") +
  geom_vline(data = data_vline_127, aes(xintercept = value), linetype="dotdash", colour = "brown1") +
labs(y = "TDG ("~OD[680]~")", x = "Elapsed time (h)") +
  scale_colour_discrete(type=c("seagreen4", "palegreen3", "brown1", "brown4")) +
  scale_x_continuous(breaks=seq(0, 300, by = 100)) +
  coord_cartesian(xlim = c(0, 380)) +
  ggh4x::facet_nested(cols = vars(facetsPhotoperiod, Photoperiod), rows = vars(facetsPar_ue, Par_ue), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        legend.background = element_rect(fill="transparent"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        #panel.spacing.x=unit(0.9, "lines"),
        legend.position = c(0.08,0.94),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.spacing.x = unit(-0.1, 'cm'),
        legend.title = element_blank(),
        legend.text = element_text(size=10))
```

```{r Create df for vertical lines (coloured as Strain) contained tMaxAG values}
#PC-rich_056
data_vline_056 <- data.frame(Par_ue= c(180, 300, 90, 180, 300, 90, 180, 300),Photoperiod= c(8,8,12,12,12,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(266.84, 240.72, 296.45, 217.80, 191.03, 191.49, 114.95, 112.75))


#PC-rich_077
data_vline_077 <- data.frame(Par_ue= c(180, 300, 90, 180, 300, 30, 90, 180, 300),Photoperiod= c(8,8,12,12,12,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(266.9300, 215.42,  244.38, 190.39,  299.57, 168.85, 137.50, 112.29))

#PE-rich_048
data_vline_048 <- data.frame(Par_ue= c(90, 180, 300, 90, 180, 300, 900,30, 90, 180, 300, 900),Photoperiod= c(8,8,8,12,12,12,12,16,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(319.9200, 240.8100, 214.41,   216.33, 163.44, 136.03, 135.39, 299.38, 166.28, 137.32, 111.28, 109.45))

#PE-rich_127
data_vline_127 <- data.frame(Par_ue= c(90, 180, 300, 90, 180, 300, 90, 180, 300, 900),Photoperiod= c(8,8,8,12,12,12,16,16,16,16),facetsPar_ue= c("PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})","PAR~(µmol~photons~m^{-2}~s^{-1})"),facetsPhotoperiod= c("Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)","Photoperiod~(h)"), value = c(321.0200, 240.9000, 187.92,  245.39, 189.48, 162.62, 168.39, 113.76, 111.56, 135.76))
```

```{r}
293.833, 375.65, 187.7300, 353.1000, 188.1900, 355.3000, 163.4400, 

244.2500, 348.2400, 187.1800, 349.8000, 184.1600, 161.9700, 

347.1400, 187.27, 350.17, 

373.27, 187.00, 371.98, 188.38, 382.07, 

```



```{r Create TDG plot, fig.height = 8, fig.width = 8, warning = FALSE}
GScatalogMeta %>%
  filter(Photoperiod != 24) %>% 
  ggplot() +
  geom_point(aes(x = PhotoperiodTend_h, y = TDG, colour = as.factor(Strain)), size = 3.5, alpha = 0.8, show.legend = T) +
  geom_vline(data = data_vline_056, aes(xintercept = value), linetype="dotdash", colour = "seagreen4") +
  # geom_vline(data = data_vline_077, aes(xintercept = value), linetype="dotdash", colour = "palegreen3") +
  # geom_vline(data = data_vline_048, aes(xintercept = value), linetype="dotdash", colour = "brown4") +
  # geom_vline(data = data_vline_127, aes(xintercept = value), linetype="dotdash", colour = "brown1") +
labs(y = "TDG ("~OD[680]~")", x = "Elapsed time (h)") +
  scale_colour_discrete(type=c("seagreen4", "palegreen3", "brown1", "brown4")) +
  scale_x_continuous(breaks=seq(0, 300, by = 100)) +
  coord_cartesian(xlim = c(0, 380)) +
  ggh4x::facet_nested(cols = vars(facetsPhotoperiod, Photoperiod), rows = vars(facetsPar_ue, Par_ue), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        legend.background = element_rect(fill="transparent"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        #panel.spacing.x=unit(0.9, "lines"),
        legend.position = c(0.08,0.94),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.y = unit(-0.1, "cm"),
        legend.spacing.x = unit(-0.1, 'cm'),
        legend.title = element_blank(),
        legend.text = element_text(size=10))
```








Calculate real Par_ue and PARphotondoseSine based on AccLen (because of sine shape of light)

change as character to extract first digit without round - b/c this is hours
```{r}
GScatalogAllSine<-GScatalogMeta %>% 
  mutate(meanAccLen = as.character(meanAccLen)) 

  library(stringi)
GScatalogAllSine$meanAccLenRound<- substr(GScatalogAllSine$meanAccLen, 1, 1)

GScatalogAllSine<-GScatalogAllSine %>% 
  mutate(meanAccLen = as.numeric(meanAccLen)) %>% 
  mutate(meanAccLenRound = as.numeric(meanAccLenRound)) 

```
df with calculated Par_ue sine per hour
```{r}
gs4_deauth()

ParSine<- read_sheet("https://docs.google.com/spreadsheets/d/1oZLemHtd6H3j2MgXbgNzqtZ2Gy3EKH6Vnn14PnEpPTw/edit#gid=0")

as.data.frame(ParSine)
ParSine <- ParSine

ParSine<-ParSine %>%
  mutate(PAR_Sine = as.numeric(PAR_Sine)) %>%
  mutate(Par_ue = as.numeric(Par_ue)) %>%
  mutate(Photoperiod = as.numeric(Photoperiod)) %>%
  mutate(RealTime = as.numeric(RealTime)) %>%
  mutate(Photoperiod_h_Sine = as.numeric(Photoperiod_h_Sine)) %>%
  mutate(Strain=case_when(Strain=="BA127R"~"PE-rich_127",
         Strain=="BA48R"~"PE-rich_048",
        Strain=="BA56G"~"PC-rich_056",
         Strain=="BA77G"~"PC-rich_077")) %>% 
  mutate(PARPhotonDoseSine = (PAR_Sine*Photoperiod/2)*3600)

```

```{r Combine GScatalogAllSine with ParSine}
GScatalogAllSineok <- GScatalogAllSine %>%
  left_join(., ParSine, by = c("Strain" = "Strain", "Photoperiod" = "Photoperiod", "Par_ue" = "Par_ue", "meanAccLenRound" = "Photoperiod_h_Sine"))
```

```{r AccLen vs PARphotondose Plot, fig.height = 8, fig.width = 8, warning = FALSE}
scientific_10 <- function(x) {   parse(text=gsub("e\\+*", " %*% 10^", scales::scientific_format()(x))) }
lab1=c(expression("8 h"), expression("12 h"), expression("16 h"))
lab2=c(expression("30 µE"), expression("90 µE"), expression("180 µE"), expression("300 µE"), expression("900 µE"))

GScatalogAllSineok %>%
  filter(Phase != "TP") %>% 
  filter(meanAccLen>0) %>% 
  ggplot() +
  geom_point(aes(x = PARPhotonDoseSine, y = meanAccLen, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
  geom_line(aes(x = PARPhotonDoseSine, y = meanAccLen, colour = as.factor(Par_ue)), size = 0.7, show.legend = F) +
  # geom_errorbar(aes(x = PARPhotonDose, ymin = meanGS_h - sdGS_h, ymax = meanGS_h + sdGS_h, colour = as.factor(Par_ue)), show.legend = F) +
  # geom_hline(data = data_hlineGS8, aes(yintercept = value), linetype="dotted") +
  # geom_hline(data = data_hlineGS12, aes(yintercept = value), linetype="dotdash") +
  # geom_hline(data = data_hlineGS16, aes(yintercept = value), linetype="dashed") +
  #geom_hline(yintercept = 1, linetype="dashed") +
   labs(y = "AccLen (h)", x = "Real PAR photon dose ( µmol photons "~m^-2~""~d^-1~")") +
 #labs(y = "Diel growth symmetry", x = "PAR photon dose ( µmol photons "~m^-2~""~d^-1~")") +
  scale_shape_manual(values = c(15, 16, 17), name="", labels = lab1) +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  scale_x_continuous(label=scientific_10) +
  ggh4x::facet_nested(cols = vars(facetsPhase, Phase), rows = vars(facetsStrain, Strain), labeller = label_parsed) +
  theme_bw()


GScatalogAllSineok %>%
  filter(Phase != "TP") %>%
  ggplot() +
  geom_point(aes(x = PAR_Sine, y = meanAccLen, colour = as.factor(Par_ue), shape = as.factor(Photoperiod)), size = 3.5, alpha = 0.8, show.legend = T) +
  # geom_errorbar(aes(x = PARPhotonDose, ymin = meanGS_h - sdGS_h, ymax = meanGS_h + sdGS_h, colour = as.factor(Par_ue)), show.legend = F) +
#labs(y = "AccLen (h)", x = "Photoperiod (h)") +
  scale_shape_manual(values = c(15, 16, 17), name="", labels = lab1) +
  scale_colour_manual(values = c("darkslategray", "lightblue4", "hotpink4", "indianred3", "orange1"), name="", labels = lab2) +
  ggh4x::facet_nested(cols = vars(facetsPhase, Phase), rows = vars(facetsStrain, Strain), labeller = label_parsed) +
  theme_bw() 
```



```{r save rds}
# saveRDS(OLISSpectraMeta440, file.path(DataOut, paste(Project, "OlisSpectra.Rds", sep = "_"), fsep = .Platform$file.sep))
```



