---
title: "Import OLIS spectral data"
author: "Douglas A. Campbell, Sylwia Sliwinska-Wilczewska"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
---

# Import Whole-cell spectra files generated by OLIS spectrophotometer

```{r setup, include = FALSE}
# knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# knitr::opts_chunk$set(fig.path='Figs/')
```

```{r load libraries} 
library(tidyverse)
library(lubridate)
library(broom)
library(knitr)
library(OneR)
library(zoo)
library(googledrive)
library(googlesheets4)
library(readxl)
```

```{r set project variables, read zipped files, list available files, warning = FALSE, echo=FALSE}
Project <- "Baltic_Photoperiod"
DataOut <- file.path("..", "Data", "ImportedData")

# Set the path to the zip folder and the destination folder
zip_file <- file.path("..", "Data", "RawData", "OlisSpectra.zip")
#zip_file <- "C:/Users/Lenovo/Documents/GitHub/Baltic_Photoperiod/Data/RawData/OlisSpectra.zip"

#List files in the extracted folder with a ".asc" extension
OlisFiles <- unzip(zip_file, list = TRUE)
OlisFiles <- OlisFiles[grepl(".asc$", OlisFiles$Name), "Name"]
print(OlisFiles)

FileID <- "Smooth"
FileEncode <- "UTF-8" 
Delimiter <- ""
headerrows <- 0
```
```{r, set up fread_plus and read.delim_long, warning = FALSE, echo=FALSE}
# Define function to read and process each file
fread_plus <- function(Flnm, Skip, FileEncode, Delim) {
  con <- unz(zip_file, Flnm)  # Corrected the file path within the zip archive
  data <- read.table(con, skip = Skip, encoding = FileEncode, sep = Delim, header = TRUE, row.names = NULL)
  
# Use tryCatch to handle errors during the closing of the connection
  tryCatch(
    close(con),
    error = function(e) {
      warning("Error closing connection: ", e$message)
    })
  
  data <- data %>%
    mutate(Filename = Flnm, CDateTime = ymd_hms(file.info(zip_file)$ctime)) 
  return(data)
}


#read.delim_long meant for map over a vector of filepaths to read, convert to long format and tidy the imported data
read.delim_long <- function(Flnm, FileEncode, Delimiter, headerrows){
  read.delim(Flnm, encoding = FileEncode, sep = Delimiter, skip = headerrows, header = TRUE, row.names = NULL) %>%
  mutate(Filename = flnm, CDateTime = ymd_hms(file.info(flnm)$ctime)) %>%
  rename(nm = OLIS.3D.ASCII) %>%
  mutate(FirstLastSpec = str_extract(Filename, "_[A-Z][a-z][A-Z][a-z][:digit:][:digit:][:digit:][:digit:]_[A-Z][a-z][A-Z][a-z][:digit:][:digit:][:digit:][:digit:]_")) %>%
  mutate(SampleNumbers = str_extract_all(FirstLastSpec, "[:digit:][:digit:][:digit:][:digit:]")) %>%
  mutate(FirstSampleNumber = as.numeric(map(SampleNumbers, ~.[[1]]))) %>%
  mutate(LastSampleNumber = as.numeric(map(SampleNumbers, ~.[[2]]))) %>%
  mutate(OperatorID = str_extract(Filename,"[A-Z][a-z][A-Z][a-z]")) %>%
  pivot_longer(cols = starts_with("X"), names_to = "SpectraID", values_to = "Abs") %>%
  mutate(SampleCode = as.numeric(str_remove(SpectraID, "X"))) %>%
  mutate(SampleNumber = SampleCode - min(SampleCode, na.rm = TRUE) + FirstSampleNumber) %>%
  relocate(OperatorID, SampleNumber) %>%
  unite(col = SampleID, OperatorID:SampleNumber, sep = "", remove = FALSE) %>%
  arrange(SampleID, nm) %>%
  relocate(SampleID, nm, Abs) %>%
  mutate(SpectraDate = str_extract(Filename, "/[:digit:][:digit:][:digit:][:digit:][:digit:][:digit:][:digit:][:digit:]_"),
         SpectraDate = str_remove_all(SpectraDate, "_"),
         SpectraDate = str_remove_all(SpectraDate, "/"),
         SpectraDate = ymd(SpectraDate)
  )
}
```

```{r Import OLIS Spectra corrected files, warning = FALSE, echo=FALSE}
TargetFile <-  OlisFiles
TargetSpectra <- TargetFile %>% 
  map_df(~fread_plus(Flnm = ., FileEncode = FileEncode, Delim = Delimiter, Skip = headerrows)) %>% 
  pivot_longer(., -c(`OLIS.3D.ASCII`, Filename, CDateTime), values_to = "Absorbance", names_to = "SampleID") %>%
  filter(!is.na(Absorbance)) %>%
  mutate(nm = `OLIS.3D.ASCII`) %>% 
  select(-c(`OLIS.3D.ASCII`))   

TargetSpectraLong <- TargetSpectra %>%
  separate(col = Filename, into = c("fp3", "ObsDate", "Project", "CultureID", "Range", "Type", "Correction", "Smooth"), sep = "([\\/\\_\\:])", remove = FALSE) 
TargetSpectraLong <- TargetSpectraLong %>%
  select(-c(fp3, Type, Correction, Smooth, SampleID, Project)) %>% 
  mutate(ObsDate = ymd(`ObsDate`))
```

```{r load local multiculticatalog, message = FALSE, warning = FALSE, echo=FALSE}
gs4_deauth()

MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1y144Qjs1pxO2vYU4G6of69qX1TVlA8WTwnhfVwaSU0U/edit#gid=0") %>%
  drop_na(WL) %>%
  mutate(WL = unlist(WL))

as.data.frame(MetaData)
MetaData <- MetaData %>%
   mutate(ExpDate = ymd(ExpDate),
          ExpEndDate = ymd_hms(`ExpEndDate`))
```

```{r Merge OLISSpectra with MetaData}
OLISSpectraMeta <- MetaData %>%
  left_join(., TargetSpectraLong, by = c("CultureID" = "CultureID")) 

OLISSpectraMeta <- OLISSpectraMeta %>%
group_by(CultureID) %>%
  arrange(ObsDate) %>%
  mutate(E_days = as.numeric((ObsDate - ExpDate[1]))) %>%
  mutate(SumAb = sum(Absorbance)) %>% 
ungroup()

OLISSpectraMeta <- OLISSpectraMeta %>%
  filter(nm >= 400 & nm <= 700)
```

```{r Normalization at 440 }
Absorbance440 <- OLISSpectraMeta %>% 
  filter(nm == 440) %>%
  mutate(Abs440 = Absorbance) %>%
  select(CultureID, Strain, Abs440, Par_ue, Photoperiod, E_days)
  
OLISSpectraMeta440 <- OLISSpectraMeta %>%
  left_join(., Absorbance440) %>%
  mutate(AbsNorm440 = Absorbance / Abs440) 
  
OLISSpectraMeta440 <- OLISSpectraMeta440 %>%
group_by(CultureID, E_days, Par_ue, Photoperiod) %>%
  mutate(SumAbNorm = sum(AbsNorm440)) %>% 
ungroup()
```

```{r cleaning and ordering OLIS SpectraMeta440 for final rds}
OLISSpectraMeta440<-OLISSpectraMeta440 %>% 
  mutate(FilenameOlis=Filename) %>% 
  select(-c(CDateTime, Range, Filename)) %>% 
  select(c(Run, CultureID, Strain, InnocDate, ExpDate, Par_ue, Photoperiod, PARPhotonDose, MC, Tube, O2, WL, LightShape, ExpEndDate, FilenameOlis, ObsDate, Absorbance, nm, E_days, SumAb, Abs440, AbsNorm440, SumAbNorm))
```

```{r Removed unnecessary files from environment}
rm(Absorbance440, MetaData, TargetSpectra, OLISSpectraMeta, TargetSpectraLong)
```

```{r save rds}
saveRDS(OLISSpectraMeta440, file.path(DataOut, paste(Project, "Imported_OlisSpectra.Rds", sep = "_"), fsep = .Platform$file.sep), ascii = FALSE, version = NULL, compress = "xz", refhook = NULL)
```

