---
title: "Import OLIS spectral data data"
author: "Sylwia Sliwinska-Wilczewska"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
---



```{r setup, include = FALSE}
# knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# knitr::opts_chunk$set(fig.path='Figs/')
```

```{r set project variables}
Project <- "PicoBaltic"
DataOut <- file.path("..", "ImportedData", "SySlmanuscriptWWPhotoperiod")
#DataIn <- file.path("..", "OLISSpectraCorr", "WWPhotoperiodSingle", fsep = .Platform$file.sep)
#FileID <- "Smooth"
FileEncode <- "UTF-8" 
Delimiter <- ""
HeaderRows <- 0
```


```{r load libraries} 
# libraries; Note check actual dependencies
library(tidyverse)
library(lubridate)
library(broom)
library(knitr)
library(OneR)

#library(googledrive)
#library(googlesheets4)
library(readxl)

library(ggspectra)
library(ggpubr)
library(caret)

library(photobiologyWavebands)
library(reshape2)
library(photobiology)

library(RColorBrewer)
library(scales)

library(reshape)
library(Cairo) #for greek symbols

```


```{r set colours}
Wavelengths_nm = c(445, 470, 505, 535, 590)
Colours_nm = c("darkblue", "dodgerblue", "darkgreen", "yellowgreen",  "darkorange")

names(Colours_nm) <- Wavelengths_nm
Colours_nm

```

Load Multiculti catalog
```{r load local multiculticatalog, message = FALSE, warning = FALSE, echo=FALSE}
# gs4_deauth()
# 
# MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1ZXpwR7Gfto-uRzVdXzMpQF4frbrvMLH_IyLqonFZRSw/edit#gid=0") %>%
#   drop_na(WL) %>%
#   mutate(WL = unlist(WL))
# 
# as.data.frame(MetaData)
# MetaData <- MetaData %>%
#    mutate(ExpDate = ymd(ExpDate),
#           ExpEndDate = ymd_hms(`ExpEndDate`))
# 
# saveRDS(.....)

readRDS(xxxxx)
```


Open prevoius WWphotoperiod Rds 
```{r}
Project <- "PicoBaltic"
DataIn <- file.path("..", "ImportedData", "SySlmanuscriptWWPhotoperiod", fsep = .Platform$file.sep)
FileEncode <- "UTF-8"
Delimiter <- ","
HeaderRows <- 0
```


Exported Rmd only first time in session (I will clean this later)
```{r}
list.files(path = DataIn, pattern = Project, full.names = TRUE)
```
OLIS SPECTRA


Load previous choosen Olis file - for nice plot
```{r read ProcessFile}
#File choosen for spectra plot - 4 spectra only
OLISSpectraShortFile <- "../ImportedData/SySlmanuscriptWWPhotoperiod/PicoBaltic_OLISSpectraMetaAllPURShort.Rds"
OLISSpectraShortFileName <- str_split(string = OLISSpectraShortFile, "/")[[1]][3] %>%
  str_remove(pattern = ".Rds")
OLISSpectraShort <- readRDS(OLISSpectraShortFile)  %>%
  ungroup()

```

Changes in strain names - for nice plot
```{r}
OLISSpectraShort <- OLISSpectraShort %>%
      mutate(Strain=case_when(Strain=="BA127R"~"PE-rich_127",
         Strain=="BA48R"~"PE-rich_048",
        Strain=="BA56G"~"PC-rich_056",
         Strain=="BA77G"~"PC-rich_077"))
```

OLISSpectraMetaAllPURShort -> File choosen for spectra plot - 4 spectra only
Olis Plot
```{r fig.height = 6, fig.width = 8}

Par_ue.labs <- c("30 µE", "90 µE", "180 µE", "Phase of growth", "900 µE")
names(Par_ue.labs) <- c("30", "90", "180", "300", "900")

Photoperiod.labs <- c("8 h", "Photoperiod: 12 h", "16 h", "24 h")
names(Photoperiod.labs) <- c("8", "12", "16", "24")

E_days.labs <- c("Exponential", "Pre-stationary")
names(E_days.labs) <- c("3", "7")

Strain.labs <- c("PE-rich_127", "PC-rich_077")
names(Strain.labs) <- c("PE-rich_127", "PC-rich_077")

data_textPUR0 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PE-rich_127", "PE-rich_127"), Photoperiod = c(12), label = c('PAR = 300 µE', 'PAR = 300 µE'))

data_textPUR1 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PE-rich_127", "PE-rich_127"), Photoperiod = c(12), label = c('PUR (PE-rich) = 176 µE', 'PUR (PE-rich) = 129 µE'))

data_textPUR2 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PE-rich_127", "PE-rich_127"), Photoperiod = c(12), label = c('PUR (PC-rich) = 139 µE', 'PUR (PC-rich) = 128 µE'))

data_textpigment1 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('Chl a 440 nm'))
data_textpigment2 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('PEB-rich PE 570 nm'))
data_textpigment3 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('Chl a 680 nm'))
data_textpigment4 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('PCB-rich PC 620 nm'))
data_textpigment5 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('Car 480 nm'))
data_textpigment6 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), label = c('PUB-rich PE or PC 500 nm'))

arrowdf1 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)
arrowdf2 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)
arrowdf3 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)
arrowdf4 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)
arrowdf5 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)
arrowdf6 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300)


OLISSpectraShort %>%
  filter(Photoperiod == "12") %>%
  filter(Strain == "PE-rich_127" | Strain == "PC-rich_077") %>%
  filter(Par_ue == 300) %>%
  filter(E_days == "3" | E_days == "7") %>%
  ggplot() +
  geom_area(aes(x = nm, y = EmNormJaz439, fill = "gray84"), alpha = 0.6, show.legend = F) +
  geom_area(aes(x = nm, y = PURNormBA127R, fill = "brown4"), alpha = 0.5, show.legend = F) +
  geom_area(aes(x = nm, y = PURNormBA77G, fill = "palegreen3"), alpha = 0.5, show.legend = F) +
  geom_line(aes(x = nm, y = AbsNorm440, colour = as.factor(Strain), linetype = as.factor(Strain)), show.legend = F, size = 0.7) +

  geom_text(data=data_textPUR0, aes(x=435, y=1.26, label=label), size=3.5) +
  geom_text(data=data_textPUR1, aes(x=462, y=1.21, label=label), size=3.5) +
  geom_text(data=data_textPUR2, aes(x=462, y=1.16, label=label), size=3.5) +

  geom_text(data=data_textpigment1, aes(x=450, y=1.07, label=label), size=4, colour = "darkgreen") + #chla440
  geom_text(data=data_textpigment5, aes(x=430, y=0.36, label=label), size=4, colour = "coral3") + #Car
  geom_text(data=data_textpigment2, aes(x=520, y=0.92, label=label), size=4, colour = "darkmagenta") + #PE
  geom_text(data=data_textpigment3, aes(x=660, y=1.08, label=label), size=4, colour = "darkgreen") +#chla680
  geom_text(data=data_textpigment4, aes(x=605, y=1.0, label=label), size=4, colour = "deepskyblue4") + #PC
  geom_text(data=data_textpigment6, aes(x=485, y=0.08, label=label), size=4, colour = "sienna4") + #PUB

  geom_segment(data = arrowdf1,
               aes(x = 470, xend = 440, y = 1.04, yend = 1.02),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla440
    geom_segment(data = arrowdf5,
               aes(x = 450, xend = 470, y = 0.4, yend = 0.48),
               colour = "coral3", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #Car
  geom_segment(data = arrowdf2,
               aes(x = 538, xend = 568, y = 0.88, yend = 0.86),
               colour = "darkmagenta", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PE
  geom_segment(data = arrowdf3,
               aes(x = 697, xend = 680, y = 1.05, yend = 0.92),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla680
  geom_segment(data = arrowdf4,
               aes(x = 632, xend = 630, y = 0.95, yend = 0.82),
               colour = "deepskyblue4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PC
  geom_segment(data = arrowdf4,
               aes(x = 465, xend = 500, y = 0.12, yend = 0.52),
               colour = "sienna4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PUB
  
  # scale_color_manual(values = c("BA127R" ="black", "BA48R" ="brown1", "BA56G" ="palegreen4", "BA77G" ="black")) +
  scale_color_manual(values = c("PE-rich_127" ="brown4", "PC-rich_077" ="palegreen3")) +
  scale_linetype_manual(values = c("PE-rich_127" ="longdash", "PC-rich_077" ="solid")) +
  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = -0.025, alpha = 0.5) + 
  scale_fill_identity() +
  
  labs(y = "Normalized absorbance", x = "Wavelength (nm)") +
  scale_y_continuous(breaks=seq(0, 1.2, by = 0.4)) +
  coord_cartesian(ylim = c (-0.01, 1.25)) +

  
  ggh4x::facet_nested(cols = vars(Par_ue, E_days), labeller = labeller(Ex_WL = label_both, WL = label_both, E_days = E_days.labs, Photoperiod = Photoperiod.labs, Par_ue = Par_ue.labs, Strain = Strain.labs)) +
  
  theme_bw() +
      theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          panel.spacing.x = unit(0.4, 'cm'),
        axis.text = element_text(size=12),
        axis.text.x = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank(),
        legend.direction="horizontal",
        legend.position = c(0.08,0.97),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text.align = 0,
        #legend.key.height= unit(0.005, 'cm'),
        legend.key.width= unit(0.3, 'cm'),
        #plot.background = element_rect(colour = "dodgerblue4", size = 3),
        legend.text = element_text(size=10))

#ggsave(filename = file.path("..", "Output", "Plots", "WholeCellSpectra.png"), plot = WholeCellSpectraPlot)

ggsave(filename = file.path("..", "Output", "Plots", "WholeCellSpectra.png"), plot = last_plot())


```

# Olis Plot
```{r fig.height = 10, fig.width = 8}
Par_ue.labs <- c("30 µE", "90 µE", "180 µE", "Phase of growth", "900 µE")
names(Par_ue.labs) <- c("30", "90", "180", "300", "900")

Photoperiod.labs <- c("8 h", "Photoperiod: 12 h", "16 h", "24 h")
names(Photoperiod.labs) <- c("8", "12", "16", "24")

E_days.labs <- c("Exponential", "Pre-stationary")
names(E_days.labs) <- c("3", "7")

Strain.labs <- c("PC-rich", "PE-rich")
names(Strain.labs) <- c("PC-rich_077", "PE-rich_127")

O2.labs <- c("Strain")
names(O2.labs) <- c(21)

data_textPUR0 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PE-rich_127", "PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('PAR = 300 µE', 'PAR = 300 µE'))

data_textPUR00 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PC-rich_077", "PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('PAR = 300 µE', 'PAR = 300 µE'))

data_textPUR1 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PE-rich_127", "PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('PUR = 176 µE', 'PUR = 129 µE'))

data_textPUR2 <- data.frame(Par_ue = c(300, 300), E_days = c(3, 7), Strain  = c("PC-rich_077", "PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('PUR = 139 µE', 'PUR = 128 µE'))

data_textpigment1 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('Chl a 440 nm'))
data_textpigment3 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('Chl a 680 nm'))
data_textpigment4 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('PCB-rich PC 620 nm'))
data_textpigment5 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('Car 480 nm'))
data_textpigment6 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PC-rich_077"), Photoperiod = c(12), O2 = c(21), label = c('PUB-rich PC 500 nm'))

arrowdf1 <- tibble(Strain = "PC-rich_077", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf3 <- tibble(Strain = "PC-rich_077", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf4 <- tibble(Strain = "PC-rich_077", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf5 <- tibble(Strain = "PC-rich_077", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf6 <- tibble(Strain = "PC-rich_077", E_days = 3, Par_ue = 300, O2 = c(21))


data_textpigment7 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('Chl a 440 nm'))
data_textpigment8 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('Car 480 nm'))
data_textpigment9 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('PEB-rich PE 570 nm'))
data_textpigment10 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('Chl a 680 nm'))
data_textpigment11 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('PCB-rich PC 620 nm'))
data_textpigment12 <- data.frame(Par_ue = c(300), E_days = c(3), Strain  = c("PE-rich_127"), Photoperiod = c(12), O2 = c(21), label = c('PUB-rich PE 500 nm'))

arrowdf7 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf8 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf9 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf10 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf11 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))
arrowdf12 <- tibble(Strain = "PE-rich_127", E_days = 3, Par_ue = 300, O2 = c(21))


Plot <- OLISSpectraShort %>%
  filter(Photoperiod == "12") %>%
  filter(Strain == "PC-rich_077" | Strain == "PE-rich_127") %>%
  filter(Par_ue == 300) %>%
  filter(E_days == "3" | E_days == "7") %>%
  ggplot() +

  geom_area(aes(x = nm, y = EmNormJaz439, fill = "gray84"), alpha = 0.6, show.legend = F) +
  geom_area(aes(x = nm, y = PURNormBA127R, fill = "brown4"), alpha = 0.5, show.legend = F) +
  geom_area(aes(x = nm, y = PURNormBA77G, fill = "palegreen3"), alpha = 0.5, show.legend = F) +
  geom_line(aes(x = nm, y = AbsNorm440, colour = as.factor(Strain), linetype = as.factor(Strain)), show.legend = F, size = 0.7) +

  geom_text(data=data_textPUR0, aes(x=446, y=1.26, label=label), size=3.7) +
  geom_text(data=data_textPUR00, aes(x=446, y=1.26, label=label), size=3.7) +
  geom_text(data=data_textPUR1, aes(x=446, y=1.21, label=label), size=3.7) +
  geom_text(data=data_textPUR2, aes(x=446, y=1.21, label=label), size=3.7) +

  geom_text(data=data_textpigment1, aes(x=500, y=1.1, label=label), size=4, colour = "darkgreen") + #chla440
  geom_text(data=data_textpigment5, aes(x=500, y=0.8, label=label), size=4, colour = "orange") + #Car
  geom_text(data=data_textpigment3, aes(x=650, y=1.2, label=label), size=4, colour = "darkgreen") +#chla680
  geom_text(data=data_textpigment4, aes(x=590, y=0.95, label=label), size=4, colour = "deepskyblue4") + #PC
  geom_text(data=data_textpigment6, aes(x=485, y=0.25, label=label), size=4, colour = "sienna4") + #PUB

  geom_segment(data = arrowdf1,
               aes(x = 480, xend = 445, y = 1.05, yend = 1),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla440
  geom_segment(data = arrowdf5,
               aes(x = 480, xend = 475, y = 0.75, yend = 0.54),
               colour = "orange", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #Car
  geom_segment(data = arrowdf3,
               aes(x = 660, xend = 680, y = 1.14, yend = 0.95),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla680
  geom_segment(data = arrowdf4,
               aes(x = 610, xend = 630, y = 0.90, yend = 0.82),
               colour = "deepskyblue4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PC
  geom_segment(data = arrowdf4,
               aes(x = 480, xend = 494, y = 0.30, yend = 0.41),
               colour = "sienna4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PUB

  
  geom_text(data=data_textpigment7, aes(x=500, y=1.1, label=label), size=4, colour = "darkgreen") + #chla440
  geom_text(data=data_textpigment8, aes(x=500, y=0.8, label=label), size=4, colour = "orange") + #Car
  geom_text(data=data_textpigment9, aes(x=580, y=1.0, label=label), size=4, colour = "darkmagenta") + #PE
  geom_text(data=data_textpigment10, aes(x=650, y=1.2, label=label), size=4, colour = "darkgreen") +#chla680
  geom_text(data=data_textpigment11, aes(x=600, y=0.17, label=label), size=4, colour = "deepskyblue4") + #PC
  geom_text(data=data_textpigment12, aes(x=495, y=0.30, label=label), size=4, colour = "sienna4") + #PUB

  geom_segment(data = arrowdf7,
               aes(x = 480, xend = 445, y = 1.05, yend = 1),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla440
  geom_segment(data = arrowdf8,
               aes(x = 480, xend = 475, y = 0.75, yend = 0.55),
               colour = "orange", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #Car
  geom_segment(data = arrowdf9,
               aes(x = 590, xend = 575, y = 0.95, yend = 0.85),
               colour = "darkmagenta", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PE
  geom_segment(data = arrowdf10,
               aes(x = 660, xend = 680, y = 1.14, yend = 0.85),
               colour = "darkgreen", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #chla680
  geom_segment(data = arrowdf11,
               aes(x = 610, xend = 630, y = 0.2, yend = 0.3),
               colour = "deepskyblue4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PC
  geom_segment(data = arrowdf12,
               aes(x = 490, xend = 500, y = 0.35, yend = 0.52),
               colour = "sienna4", size = 1, alpha=0.9, arrow = arrow(length=unit(0.2, 'cm'))) + #PUB
  
  
  
  scale_color_manual(values = c("PC-rich_077" ="palegreen3", "PE-rich_127" ="brown4")) +
  scale_linetype_manual(values = c("PC-rich_077" ="solid", "PE-rich_127" ="longdash")) +

  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = -0.025, alpha = 0.5) +
  scale_fill_identity() +

  labs(y = "Normalized absorbance", x = "Wavelength (nm)") +
  scale_y_continuous(breaks=seq(0, 1.2, by = 0.4)) +
  coord_cartesian(ylim = c (-0.01, 1.25)) +
  ggh4x::facet_nested(cols = vars(Par_ue, E_days), rows = vars(O2, Strain),labeller = labeller(Ex_WL = label_both, WL = label_both, E_days = E_days.labs, Photoperiod = Photoperiod.labs, Par_ue = Par_ue.labs, Strain = Strain.labs, O2 = O2.labs, )) +
  theme_bw() +
      theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          panel.spacing.x = unit(0.4, 'cm'),
        axis.text = element_text(size=12),
        axis.text.x = element_text(size=12),
        axis.title = element_text(size=16),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=12),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank(),
        legend.direction="horizontal",
        legend.position = c(0.08,0.97),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text.align = 0,
        #legend.key.height= unit(0.005, 'cm'),
        legend.key.width= unit(0.3, 'cm'),
        #plot.background = element_rect(colour = "dodgerblue4", size = 3),
        legend.text = element_text(size=10))
Plot


```
Delete unused stuff from environment
```{r}

rm(data_textpigment1,data_textpigment2,data_textpigment3,data_textpigment4,data_textpigment5,data_textpigment6, data_textpigment7, data_textpigment8, data_textpigment9, data_textpigment10, data_textpigment11, data_textpigment12, arrowdf1,arrowdf2,arrowdf3,arrowdf4,arrowdf5,arrowdf6, arrowdf7, arrowdf8, arrowdf9, arrowdf10, arrowdf11, arrowdf12, data_textPUR0, data_textPUR00, data_textPUR1,data_textPUR2)

```

